name: cadence_tool
publish_to: none
resolution: workspace
environment:
  sdk: ^3.12.2
dependencies:
  args: ^2.7.0
  file: ^7.0.1
  path: ^1.9.0
  liquify: ^1.6.1
  archive: ^4.0.0
  crypto: ^3.0.7
  cadence_client:
    path: ../packages/client
dev_dependencies:
  test: ^1.25.0
